<#
.SYNOPSIS
    Generate a WinSparkle appcast.xml for Reflection releases.

.DESCRIPTION
    Signs the installer with Ed25519 via winsparkle-tool and generates an
    appcast XML file compatible with WinSparkle/Sparkle. The appcast contains
    the version, download URL, Ed25519 signature, file size, and publication date.

    Called by the release workflow (release.yml) after the installer is built.

.PARAMETER Version
    Release version string (e.g., "1.7.0"). Must match the git tag (without "v" prefix).

.PARAMETER InstallerPath
    Absolute path to the Inno Setup installer .exe to sign and reference.

.PARAMETER PrivateKeyPath
    Path to the Ed25519 private key file (generated by winsparkle-tool generate-key).

.PARAMETER WinSparkleToolPath
    Path to winsparkle-tool.exe (from the WinSparkle release ZIP).

.PARAMETER OutputPath
    Where to write the generated appcast.xml file.

.PARAMETER RepoUrl
    GitHub repository URL (e.g., "https://github.com/SatanshuMishra/reflection").
    Used to construct the download URL for the installer.

.EXAMPLE
    .\generate-appcast.ps1 `
        -Version "1.7.0" `
        -InstallerPath "installer\Output\Reflection-1.7.0-Setup.exe" `
        -PrivateKeyPath "private.key" `
        -WinSparkleToolPath "bin\winsparkle-tool.exe" `
        -OutputPath "appcast.xml" `
        -RepoUrl "https://github.com/SatanshuMishra/reflection"
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory)]
    [string]$Version,

    [Parameter(Mandatory)]
    [string]$InstallerPath,

    [Parameter(Mandatory)]
    [string]$PrivateKeyPath,

    [Parameter(Mandatory)]
    [string]$WinSparkleToolPath,

    [Parameter(Mandatory)]
    [string]$OutputPath,

    [Parameter(Mandatory)]
    [string]$RepoUrl
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# Validate inputs
if (-not (Test-Path $InstallerPath)) {
    Write-Error "Installer not found: $InstallerPath"
    exit 1
}
if (-not (Test-Path $PrivateKeyPath)) {
    Write-Error "Private key not found: $PrivateKeyPath"
    exit 1
}
if (-not (Test-Path $WinSparkleToolPath)) {
    Write-Error "winsparkle-tool not found: $WinSparkleToolPath"
    exit 1
}

# Sign the installer with Ed25519
Write-Host "Signing installer with Ed25519..."
$signature = & $WinSparkleToolPath sign -f $PrivateKeyPath $InstallerPath 2>&1
if ($LASTEXITCODE -ne 0) {
    Write-Error "winsparkle-tool sign failed: $signature"
    exit 1
}
$signature = $signature.Trim()
Write-Host "Signature: $signature"

# Get file size
$fileSize = (Get-Item $InstallerPath).Length
Write-Host "File size: $fileSize bytes"

# Get installer filename for the download URL
$installerName = [System.IO.Path]::GetFileName($InstallerPath)

# Generate RFC 822 date (required by RSS 2.0 <pubDate>)
$pubDate = (Get-Date).ToUniversalTime().ToString("ddd, dd MMM yyyy HH:mm:ss 'GMT'",
    [System.Globalization.CultureInfo]::InvariantCulture)

# Construct download URL
$downloadUrl = "$RepoUrl/releases/download/v$Version/$installerName"

# Generate appcast XML
$appcastXml = @"
<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0" xmlns:sparkle="http://www.andymatuschak.org/xml-namespaces/sparkle">
  <channel>
    <title>Reflection Updates</title>
    <description>Reflection for Windows update feed</description>
    <language>en</language>
    <item>
      <title>Version $Version</title>
      <sparkle:version>$Version</sparkle:version>
      <pubDate>$pubDate</pubDate>
      <enclosure
        url="$downloadUrl"
        sparkle:os="windows-x64"
        sparkle:edSignature="$signature"
        sparkle:installerArguments="/VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP-"
        length="$fileSize"
        type="application/octet-stream" />
    </item>
  </channel>
</rss>
"@

# Write appcast to output file
$appcastXml | Out-File -FilePath $OutputPath -Encoding utf8
Write-Host "Appcast written to: $OutputPath"
Write-Host "  Version:    $Version"
Write-Host "  URL:        $downloadUrl"
Write-Host "  Signature:  $($signature.Substring(0, 20))..."
Write-Host "  File size:  $fileSize"
Write-Host "  Date:       $pubDate"
